apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mailbaby.fullname" . }}-config
  labels:
    {{- include "mailbaby.labels" . | nindent 4 }}
data:
  config.yaml: |
{{- if .Values.config.customYaml }}
{{ .Values.config.customYaml | indent 4 }}
{{- else }}
{{ .Values.config | toYaml | indent 4 }}
{{- end }}
