{{- if and .Values.secret.enabled (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mailbaby.fullname" . }}-secret
  labels:
    {{- include "mailbaby.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secret.authSecretKey }}
  auth-secret-key: {{ .Values.secret.authSecretKey | b64enc | quote }}
  {{- end }}
  {{- range $account, $password := .Values.secret.smtpPasswords }}
  smtp-password-{{ $account }}: {{ $password | b64enc | quote }}
  {{- end }}
{{- end }}
